[phases.setup]
ubuntuPkgs = ["git"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "rm -rf ../backend/frontend",
  "mkdir -p ../backend/frontend",
  "cp -r frontend/dist/* ../backend/frontend/"
]

[start]
cmd = "node backend/server.js"